title: Muhammet Emin Ölçüm

logo: /src/Image.JPG

description: '<a href="https://www.linkedin.com/in/muhammeteminolcum/" target="_blank">LinkedIn</a> | <a href="https://github.com/eminolcum/" target="_blank">GitHub</a>'

show_downloads: False

theme: jekyll-theme-minimal


