title: Muhammet Emin Ölçüm

logo: /src/Image.JPG

description: '<a href="https://www.linkedin.com/in/muhammeteminolcum/" target="_blank">LinkedIn</a>'

show_downloads: False

theme: jekyll-theme-minimal


